project_id = "appthinkanas"

[auth]
site_url = "https://thinkanas.com"
additional_redirect_urls = ["https://thinkanas.com/acces"]

[auth.passkey]
enabled = true

[auth.webauthn]
rp_display_name = "think.anas"
rp_id = "thinkanas.com"
rp_origins = ["https://thinkanas.com"]
