/**
 * Banque de mots du rituel.
 *
 * Un lemme français = une entrée, traduite une fois pour toutes. Les citations
 * y piochent ; un mot qui revient dans trois citations n'est écrit qu'ici, donc
 * jamais deux traductions divergentes du même mot.
 *
 * Les noms portent leur article (el/la, der/die/das) : un nom appris sans son
 * genre est un nom à moitié appris — et c'est précisément ce que sanctionnent
 * le DELE et le Goethe-Zertifikat.
 */

/** [français, anglais, espagnol, allemand] */
export type Entree = [string, string, string, string];

export const lexique: Record<string, Entree> = {
  // — Travail, effort, métier —
  travail: ["le travail", "work", "el trabajo", "die Arbeit"],
  effort: ["l'effort", "effort", "el esfuerzo", "die Anstrengung"],
  tache: ["la tâche", "task", "la tarea", "die Aufgabe"],
  oeuvre: ["l'œuvre", "work, deed", "la obra", "das Werk"],
  acte: ["l'acte", "act, deed", "el acto", "die Tat"],
  main: ["la main", "hand", "la mano", "die Hand"],
  metier: ["le métier", "craft, trade", "el oficio", "der Beruf"],
  outil: ["l'outil", "tool", "la herramienta", "das Werkzeug"],
  discipline: ["la discipline", "discipline", "la disciplina", "die Disziplin"],
  rigueur: ["la rigueur", "rigour", "el rigor", "die Strenge"],
  soin: ["le soin", "care", "el cuidado", "die Sorgfalt"],
  excellence: ["l'excellence", "excellence", "la excelencia", "die Exzellenz"],
  maitrise: ["la maîtrise", "mastery", "el dominio", "die Beherrschung"],
  competence: ["la compétence", "skill", "la competencia", "die Fähigkeit"],
  habitude: ["l'habitude", "habit", "el hábito", "die Gewohnheit"],
  routine: ["la routine", "routine", "la rutina", "die Routine"],
  exercice: ["l'exercice", "exercise", "el ejercicio", "die Übung"],
  entrainement: ["l'entraînement", "training", "el entrenamiento", "das Training"],
  repetition: ["la répétition", "repetition", "la repetición", "die Wiederholung"],
  fatigue: ["la fatigue", "tiredness", "el cansancio", "die Müdigkeit"],
  repos: ["le repos", "rest", "el descanso", "die Ruhe"],
  nourriture: ["la nourriture", "food", "la comida", "das Essen"],
  richesse: ["la richesse", "wealth", "la riqueza", "der Reichtum"],
  compte: ["le compte", "account, reckoning", "la cuenta", "die Rechnung"],

  // — Constance, caractère —
  constance: ["la constance", "steadiness", "la constancia", "die Beständigkeit"],
  perseverance: ["la persévérance", "perseverance", "la perseverancia", "die Ausdauer"],
  patience: ["la patience", "patience", "la paciencia", "die Geduld"],
  endurance: ["l'endurance", "endurance", "la resistencia", "die Ausdauer"],
  courage: ["le courage", "courage", "el valor", "der Mut"],
  volonte: ["la volonté", "will", "la voluntad", "der Wille"],
  force: ["la force", "strength", "la fuerza", "die Kraft"],
  faiblesse: ["la faiblesse", "weakness", "la debilidad", "die Schwäche"],
  lenteur: ["la lenteur", "slowness", "la lentitud", "die Langsamkeit"],
  precipitation: ["la précipitation", "haste", "la prisa", "die Eile"],
  humilite: ["l'humilité", "humility", "la humildad", "die Demut"],
  sincerite: ["la sincérité", "sincerity", "la sinceridad", "die Aufrichtigkeit"],
  nature: ["la nature", "nature", "la naturaleza", "die Natur"],

  // — Temps —
  temps: ["le temps", "time", "el tiempo", "die Zeit"],
  jour: ["le jour", "day", "el día", "der Tag"],
  matin: ["le matin", "morning", "la mañana", "der Morgen"],
  soir: ["le soir", "evening", "la tarde", "der Abend"],
  heure: ["l'heure", "hour", "la hora", "die Stunde"],
  semaine: ["la semaine", "week", "la semana", "die Woche"],
  mois: ["le mois", "month", "el mes", "der Monat"],
  annee: ["l'année", "year", "el año", "das Jahr"],
  debut: ["le début", "beginning", "el comienzo", "der Anfang"],
  fin: ["la fin", "end", "el fin", "das Ende"],
  moment: ["le moment", "moment", "el momento", "der Moment"],
  avenir: ["l'avenir", "future", "el futuro", "die Zukunft"],
  passe: ["le passé", "past", "el pasado", "die Vergangenheit"],
  vie: ["la vie", "life", "la vida", "das Leben"],
  siecle: ["le siècle", "century", "el siglo", "das Jahrhundert"],

  // — Savoir, étude —
  savoir: ["le savoir", "knowledge", "el saber", "das Wissen"],
  connaissance: ["la connaissance", "knowledge", "el conocimiento", "die Kenntnis"],
  science: ["la science", "science", "la ciencia", "die Wissenschaft"],
  etude: ["l'étude", "study", "el estudio", "das Studium"],
  apprentissage: ["l'apprentissage", "learning", "el aprendizaje", "das Lernen"],
  lecon: ["la leçon", "lesson", "la lección", "die Lektion"],
  livre: ["le livre", "book", "el libro", "das Buch"],
  lettre: ["la lettre", "letter", "la carta", "der Brief"],
  mot: ["le mot", "word", "la palabra", "das Wort"],
  phrase: ["la phrase", "sentence", "la frase", "der Satz"],
  langue: ["la langue", "language", "la lengua", "die Sprache"],
  question: ["la question", "question", "la pregunta", "die Frage"],
  reponse: ["la réponse", "answer", "la respuesta", "die Antwort"],
  verite: ["la vérité", "truth", "la verdad", "die Wahrheit"],
  erreur: ["l'erreur", "mistake", "el error", "der Fehler"],
  doute: ["le doute", "doubt", "la duda", "der Zweifel"],
  preuve: ["la preuve", "proof", "la prueba", "der Beweis"],
  raison: ["la raison", "reason", "la razón", "die Vernunft"],
  esprit: ["l'esprit", "mind", "la mente", "der Geist"],
  memoire: ["la mémoire", "memory", "la memoria", "das Gedächtnis"],
  attention: ["l'attention", "attention", "la atención", "die Aufmerksamkeit"],
  curiosite: ["la curiosité", "curiosity", "la curiosidad", "die Neugier"],
  sagesse: ["la sagesse", "wisdom", "la sabiduría", "die Weisheit"],
  ignorance: ["l'ignorance", "ignorance", "la ignorancia", "die Unwissenheit"],
  examen: ["l'examen", "exam", "el examen", "die Prüfung"],
  note: ["la note", "grade, mark", "la nota", "die Note"],
  principe: ["le principe", "principle", "el principio", "das Prinzip"],
  observation: ["l'observation", "observation", "la observación", "die Beobachtung"],
  philosophe: ["le philosophe", "philosopher", "el filósofo", "der Philosoph"],

  // — Données, machine —
  donnee: ["la donnée", "datum, data", "el dato", "die Daten"],
  chiffre: ["le chiffre", "figure, digit", "la cifra", "die Zahl"],
  mesure: ["la mesure", "measurement", "la medida", "die Messung"],
  modele: ["le modèle", "model", "el modelo", "das Modell"],
  calcul: ["le calcul", "calculation", "el cálculo", "die Berechnung"],
  analyse: ["l'analyse", "analysis", "el análisis", "die Analyse"],
  resultat: ["le résultat", "result", "el resultado", "das Ergebnis"],
  moyenne: ["la moyenne", "average", "la media", "der Durchschnitt"],
  ecart: ["l'écart", "gap, deviation", "la diferencia", "die Abweichung"],
  tendance: ["la tendance", "trend", "la tendencia", "der Trend"],
  prevision: ["la prévision", "forecast", "la previsión", "die Vorhersage"],
  information: ["l'information", "information", "la información", "die Information"],
  machine: ["la machine", "machine", "la máquina", "die Maschine"],
  ordinateur: ["l'ordinateur", "computer", "el ordenador", "der Computer"],
  code: ["le code", "code", "el código", "der Code"],
  intelligence: ["l'intelligence", "intelligence", "la inteligencia", "die Intelligenz"],
  reseau: ["le réseau", "network", "la red", "das Netzwerk"],
  precision: ["la précision", "accuracy", "la precisión", "die Genauigkeit"],
  echantillon: ["l'échantillon", "sample", "la muestra", "die Stichprobe"],
  experience: ["l'expérience", "experiment, experience", "el experimento", "das Experiment"],
  electricite: ["l'électricité", "electricity", "la electricidad", "die Elektrizität"],
  petrole: ["le pétrole", "oil", "el petróleo", "das Erdöl"],
  opinion: ["l'opinion", "opinion", "la opinión", "die Meinung"],
  hasard: ["le hasard", "chance", "el azar", "der Zufall"],

  // — Santé —
  sante: ["la santé", "health", "la salud", "die Gesundheit"],
  maladie: ["la maladie", "illness", "la enfermedad", "die Krankheit"],
  malade: ["le malade", "sick person", "el enfermo", "der Kranke"],
  medecin: ["le médecin", "doctor", "el médico", "der Arzt"],
  patient: ["le patient", "patient", "el paciente", "der Patient"],
  remede: ["le remède", "remedy", "el remedio", "das Heilmittel"],
  guerison: ["la guérison", "recovery", "la curación", "die Heilung"],
  douleur: ["la douleur", "pain", "el dolor", "der Schmerz"],
  corps: ["le corps", "body", "el cuerpo", "der Körper"],
  hopital: ["l'hôpital", "hospital", "el hospital", "das Krankenhaus"],
  diagnostic: ["le diagnostic", "diagnosis", "el diagnóstico", "die Diagnose"],
  prevention: ["la prévention", "prevention", "la prevención", "die Vorbeugung"],
  sommeil: ["le sommeil", "sleep", "el sueño", "der Schlaf"],
  energie: ["l'énergie", "energy", "la energía", "die Energie"],
  soulagement: ["le soulagement", "relief", "el alivio", "die Erleichterung"],

  // — Foi, morale —
  foi: ["la foi", "faith", "la fe", "der Glaube"],
  confiance: ["la confiance", "trust", "la confianza", "das Vertrauen"],
  intention: ["l'intention", "intention", "la intención", "die Absicht"],
  priere: ["la prière", "prayer", "la oración", "das Gebet"],
  coeur: ["le cœur", "heart", "el corazón", "das Herz"],
  ame: ["l'âme", "soul", "el alma", "die Seele"],
  gratitude: ["la gratitude", "gratitude", "la gratitud", "die Dankbarkeit"],
  justice: ["la justice", "justice", "la justicia", "die Gerechtigkeit"],
  injustice: ["l'injustice", "injustice", "la injusticia", "die Ungerechtigkeit"],
  epreuve: ["l'épreuve", "ordeal, test", "la prueba", "die Prüfung"],
  difficulte: ["la difficulté", "difficulty", "la dificultad", "die Schwierigkeit"],
  facilite: ["la facilité", "ease", "la facilidad", "die Leichtigkeit"],
  espoir: ["l'espoir", "hope", "la esperanza", "die Hoffnung"],
  peur: ["la peur", "fear", "el miedo", "die Angst"],
  haine: ["la haine", "hatred", "el odio", "der Hass"],
  violence: ["la violence", "violence", "la violencia", "die Gewalt"],
  monture: ["la monture", "mount, steed", "la montura", "das Reittier"],
  fruit: ["le fruit", "fruit", "el fruto", "die Frucht"],
  peuple: ["le peuple", "people", "el pueblo", "das Volk"],
  homme: ["l'homme", "man", "el hombre", "der Mensch"],
  fils: ["le fils", "son", "el hijo", "der Sohn"],
  civilisation: ["la civilisation", "civilisation", "la civilización", "die Zivilisation"],
  ruine: ["la ruine", "ruin", "la ruina", "der Ruin"],

  // — Cap, stratégie —
  but: ["le but", "goal", "la meta", "das Ziel"],
  objectif: ["l'objectif", "objective", "el objetivo", "das Ziel"],
  chemin: ["le chemin", "path", "el camino", "der Weg"],
  route: ["la route", "road", "la carretera", "die Straße"],
  pas: ["le pas", "step", "el paso", "der Schritt"],
  voyage: ["le voyage", "journey", "el viaje", "die Reise"],
  plan: ["le plan", "plan", "el plan", "der Plan"],
  projet: ["le projet", "project", "el proyecto", "das Projekt"],
  choix: ["le choix", "choice", "la elección", "die Wahl"],
  decision: ["la décision", "decision", "la decisión", "die Entscheidung"],
  priorite: ["la priorité", "priority", "la prioridad", "die Priorität"],
  obstacle: ["l'obstacle", "obstacle", "el obstáculo", "das Hindernis"],
  echec: ["l'échec", "failure", "el fracaso", "der Misserfolg"],
  reussite: ["la réussite", "success", "el éxito", "der Erfolg"],
  defaite: ["la défaite", "defeat", "la derrota", "die Niederlage"],
  risque: ["le risque", "risk", "el riesgo", "das Risiko"],
  changement: ["le changement", "change", "el cambio", "die Veränderung"],
  progres: ["le progrès", "progress", "el progreso", "der Fortschritt"],
  etape: ["l'étape", "stage", "la etapa", "die Etappe"],
  strategie: ["la stratégie", "strategy", "la estrategia", "die Strategie"],
  tactique: ["la tactique", "tactics", "la táctica", "die Taktik"],
  bruit: ["le bruit", "noise", "el ruido", "der Lärm"],
  vent: ["le vent", "wind", "el viento", "der Wind"],
  innovation: ["l'innovation", "innovation", "la innovación", "die Innovation"],
  perfection: ["la perfection", "perfection", "la perfección", "die Vollkommenheit"],
  simplicite: ["la simplicité", "simplicity", "la simplicidad", "die Einfachheit"],
  lutte: ["la lutte", "struggle", "la lucha", "der Kampf"],

  // — Verbes —
  commencer: ["commencer", "to begin", "empezar", "anfangen"],
  finir: ["finir", "to finish", "terminar", "beenden"],
  continuer: ["continuer", "to continue", "continuar", "fortsetzen"],
  avancer: ["avancer", "to move forward", "avanzar", "vorankommen"],
  arreter: ["s'arrêter", "to stop", "pararse", "anhalten"],
  tomber: ["tomber", "to fall", "caer", "fallen"],
  relever: ["se relever", "to get back up", "levantarse", "wieder aufstehen"],
  apprendre: ["apprendre", "to learn", "aprender", "lernen"],
  comprendre: ["comprendre", "to understand", "comprender", "verstehen"],
  construire: ["construire", "to build", "construir", "bauen"],
  creer: ["créer", "to create", "crear", "schaffen"],
  mesurer: ["mesurer", "to measure", "medir", "messen"],
  choisir: ["choisir", "to choose", "elegir", "wählen"],
  oser: ["oser", "to dare", "atreverse", "wagen"],
  essayer: ["essayer", "to try", "intentar", "versuchen"],
  reussir: ["réussir", "to succeed", "lograr", "gelingen"],
  echouer: ["échouer", "to fail", "fracasar", "scheitern"],
  garder: ["garder", "to keep, to guard", "guardar", "bewahren"],
  perdre: ["perdre", "to lose", "perder", "verlieren"],
  gagner: ["gagner", "to earn, to win", "ganar", "gewinnen"],
  chercher: ["chercher", "to look for", "buscar", "suchen"],
  trouver: ["trouver", "to find", "encontrar", "finden"],
  ecrire: ["écrire", "to write", "escribir", "schreiben"],
  lire: ["lire", "to read", "leer", "lesen"],
  ecouter: ["écouter", "to listen", "escuchar", "zuhören"],
  voir: ["voir", "to see", "ver", "sehen"],
  penser: ["penser", "to think", "pensar", "denken"],
  croire: ["croire", "to believe", "creer", "glauben"],
  changer: ["changer", "to change", "cambiar", "ändern"],
  durer: ["durer", "to last", "durar", "dauern"],
  repeter: ["répéter", "to repeat", "repetir", "wiederholen"],
  simplifier: ["simplifier", "to simplify", "simplificar", "vereinfachen"],
  expliquer: ["expliquer", "to explain", "explicar", "erklären"],
  prouver: ["prouver", "to prove", "probar", "beweisen"],
  decider: ["décider", "to decide", "decidir", "entscheiden"],
  soigner: ["soigner", "to treat, to care for", "cuidar", "behandeln"],
  craindre: ["craindre", "to fear", "temer", "fürchten"],
  ajouter: ["ajouter", "to add", "añadir", "hinzufügen"],
  retirer: ["retirer", "to remove", "quitar", "entfernen"],
  tromper: ["se tromper", "to be mistaken", "equivocarse", "sich irren"],
  reconnaitre: ["reconnaître", "to acknowledge", "reconocer", "anerkennen"],
  accomplir: ["accomplir", "to accomplish", "cumplir", "vollbringen"],
  transformer: ["transformer", "to transform", "transformar", "verwandeln"],
  favoriser: ["favoriser", "to favour", "favorecer", "begünstigen"],
  obtenir: ["obtenir", "to obtain", "obtener", "erhalten"],
  valoir: ["valoir", "to be worth", "valer", "wert sein"],
  manger: ["manger", "to eat", "comer", "essen"],
  attacher: ["attacher", "to tie", "atar", "binden"],
  mener: ["mener", "to lead", "llevar", "führen"],
  suivre: ["suivre", "to follow", "seguir", "folgen"],
  predire: ["prédire", "to predict", "predecir", "vorhersagen"],
  ameliorer: ["améliorer", "to improve", "mejorar", "verbessern"],
  tracer: ["tracer", "to trace, to carve out", "trazar", "bahnen"],

  // — Adjectifs —
  simple: ["simple", "simple", "simple", "einfach"],
  difficile: ["difficile", "difficult", "difícil", "schwierig"],
  facile: ["facile", "easy", "fácil", "leicht"],
  utile: ["utile", "useful", "útil", "nützlich"],
  vrai: ["vrai", "true", "verdadero", "wahr"],
  faux: ["faux", "false", "falso", "falsch"],
  fort: ["fort", "strong", "fuerte", "stark"],
  lent: ["lent", "slow", "lento", "langsam"],
  juste: ["juste", "fair, right", "justo", "gerecht"],
  clair: ["clair", "clear", "claro", "klar"],
  profond: ["profond", "deep", "profundo", "tief"],
  quotidien: ["quotidien", "daily", "diario", "täglich"],
  premier: ["premier", "first", "primero", "erste"],
  meilleur: ["meilleur", "better, best", "mejor", "besser"],
  impossible: ["impossible", "impossible", "imposible", "unmöglich"],
  prepare: ["préparé", "prepared", "preparado", "vorbereitet"],
  approximatif: ["approximatif", "approximate", "aproximado", "ungefähr"],
  exact: ["exact", "exact", "exacto", "genau"],
  precoce: ["prématuré", "premature", "prematuro", "verfrüht"],
  favorable: ["favorable", "favourable", "favorable", "günstig"],
};

export type LangueCible = "en" | "es" | "de";

export const langues: { cle: LangueCible; label: string; certificat: string; index: 1 | 2 | 3 }[] = [
  { cle: "en", label: "Anglais", certificat: "IELTS / TOEFL", index: 1 },
  { cle: "es", label: "Espagnol", certificat: "DELE", index: 2 },
  { cle: "de", label: "Allemand", certificat: "Goethe", index: 3 },
];
