/*
 * Palettes de think.anas — GÉNÉRÉ par generer_ambiances.py, ne pas modifier à la main.
 * Mêmes valeurs que les blocs [data-theme] de app/globals.css : l'ambiance « Ciel »
 * s'en sert pour fondre une palette dans la suivante, couleur par couleur.
 */

export const JETONS_COULEUR = [
  "ink",
  "ink-soft",
  "text-muted",
  "text-secondary",
  "text-tertiary",
  "hairline",
  "canvas",
  "surface-secondary",
  "surface-secondary-hover",
  "surface-warm",
  "surface-manilla",
  "surface-kraft",
  "brand",
  "brand-hover",
  "brand-soft",
  "accent-clay",
  "accent-coral",
  "accent-fig",
  "accent-cactus",
  "accent-olive",
  "accent-sky",
  "accent-heather",
  "accent-deep",
  "inverse",
  "neutre-fort",
  "neutre",
  "neutre-profond",
  "ciel-nuit",
  "ciel-aube",
  "ciel-jour",
  "ciel-crepuscule",
  "ciel-braise",
  "soleil",
  "soleil-encre",
  "isha",
  "hizb",
  "formation",
] as const;

export type JetonCouleur = (typeof JETONS_COULEUR)[number];

export type IdPalette = "clair" | "sombre" | "majorelle" | "medina" | "merzouga" | "aube" | "crepuscule";

export const PALETTES: Record<IdPalette, { sombre: boolean; couleurs: Record<JetonCouleur, string> }> = {
  clair: {
    sombre: false,
    couleurs: {
      ink: "#0f172a",
      "ink-soft": "#1e293b",
      "text-muted": "#5f6e84",
      "text-secondary": "#808da0",
      "text-tertiary": "#808da0",
      hairline: "#e8ebef",
      canvas: "#ffffff",
      "surface-secondary": "#f7f8fa",
      "surface-secondary-hover": "#f1f3f7",
      "surface-warm": "#edf0f4",
      "surface-manilla": "#fffaeb",
      "surface-kraft": "#fef3c7",
      brand: "#2563eb",
      "brand-hover": "#1d4ed8",
      "brand-soft": "#eff4ff",
      "accent-clay": "#f97316",
      "accent-coral": "#fee2e2",
      "accent-fig": "#8b5cf6",
      "accent-cactus": "#d1fae5",
      "accent-olive": "#047857",
      "accent-sky": "#3b82f6",
      "accent-heather": "#e0e7ff",
      "accent-deep": "#c81e1e",
      inverse: "#0f172a",
      "neutre-fort": "#cbd5e1",
      neutre: "#94a3b8",
      "neutre-profond": "#64748b",
      "ciel-nuit": "#e9eef5",
      "ciel-aube": "#fbe9d2",
      "ciel-jour": "#fff9ee",
      "ciel-crepuscule": "#f6dcc8",
      "ciel-braise": "#fdeada",
      soleil: "#f59e0b",
      "soleil-encre": "#b45309",
      isha: "#334155",
      hizb: "#0f766e",
      formation: "#4338ca",
    },
  },
  sombre: {
    sombre: true,
    couleurs: {
      ink: "#e8ecf3",
      "ink-soft": "#cfd6e2",
      "text-muted": "#9aa4b5",
      "text-secondary": "#6f7a8c",
      "text-tertiary": "#6f7a8c",
      hairline: "#262b36",
      canvas: "#13161d",
      "surface-secondary": "#0a0c10",
      "surface-secondary-hover": "#1a1e27",
      "surface-warm": "#242935",
      "surface-manilla": "#221e14",
      "surface-kraft": "#2b2412",
      brand: "#6b9bff",
      "brand-hover": "#8fb3ff",
      "brand-soft": "#17223a",
      "accent-clay": "#fb923c",
      "accent-coral": "#3a1a1d",
      "accent-fig": "#a78bfa",
      "accent-cactus": "#10291f",
      "accent-olive": "#34d399",
      "accent-sky": "#60a5fa",
      "accent-heather": "#1c2140",
      "accent-deep": "#f87171",
      inverse: "#e8ecf3",
      "neutre-fort": "#394150",
      neutre: "#5f6a7c",
      "neutre-profond": "#8a94a6",
      "ciel-nuit": "#0d1422",
      "ciel-aube": "#241f33",
      "ciel-jour": "#1a2030",
      "ciel-crepuscule": "#2a1e24",
      "ciel-braise": "#33222a",
      soleil: "#fbbf24",
      "soleil-encre": "#fbbf24",
      isha: "#a5b0c2",
      hizb: "#2dd4bf",
      formation: "#8f95ff",
    },
  },
  majorelle: {
    sombre: true,
    couleurs: {
      ink: "#fdf8e8",
      "ink-soft": "#f2ead0",
      "text-muted": "#c3c9f3",
      "text-secondary": "#8e98e0",
      "text-tertiary": "#8e98e0",
      hairline: "#2f3cad",
      canvas: "#1b2687",
      "surface-secondary": "#121a63",
      "surface-secondary-hover": "#222e96",
      "surface-warm": "#2a37a3",
      "surface-manilla": "#252b7a",
      "surface-kraft": "#2e3582",
      brand: "#f7c948",
      "brand-hover": "#ffd766",
      "brand-soft": "#2c3278",
      "accent-clay": "#ff9a52",
      "accent-coral": "#3b2270",
      "accent-fig": "#c4a7ff",
      "accent-cactus": "#173f63",
      "accent-olive": "#6ee7b7",
      "accent-sky": "#8ab8ff",
      "accent-heather": "#25308f",
      "accent-deep": "#ff8a8a",
      inverse: "#fdf8e8",
      "neutre-fort": "#3d4bb8",
      neutre: "#6f7bd6",
      "neutre-profond": "#a3acef",
      "ciel-nuit": "#0f1650",
      "ciel-aube": "#2b2a86",
      "ciel-jour": "#26339a",
      "ciel-crepuscule": "#3a2c85",
      "ciel-braise": "#48338a",
      soleil: "#f7c948",
      "soleil-encre": "#f7c948",
      isha: "#c7ceff",
      hizb: "#5eead4",
      formation: "#c4b5fd",
    },
  },
  medina: {
    sombre: false,
    couleurs: {
      ink: "#2a1a10",
      "ink-soft": "#3d2a1e",
      "text-muted": "#6f5646",
      "text-secondary": "#9c8471",
      "text-tertiary": "#9c8471",
      hairline: "#e3d5bf",
      canvas: "#fffaf2",
      "surface-secondary": "#f3ebdd",
      "surface-secondary-hover": "#ede1cd",
      "surface-warm": "#e6d8c2",
      "surface-manilla": "#fbf1dc",
      "surface-kraft": "#f3e2bd",
      brand: "#b1432a",
      "brand-hover": "#963520",
      "brand-soft": "#f6e3d8",
      "accent-clay": "#d9772b",
      "accent-coral": "#f7ddd3",
      "accent-fig": "#7d4e8f",
      "accent-cactus": "#d9ecdf",
      "accent-olive": "#1b6e51",
      "accent-sky": "#2f6f8f",
      "accent-heather": "#ece2ef",
      "accent-deep": "#b3261e",
      inverse: "#2a1a10",
      "neutre-fort": "#d6c6ae",
      neutre: "#b39d84",
      "neutre-profond": "#8a735e",
      "ciel-nuit": "#e8ded0",
      "ciel-aube": "#f5dcc4",
      "ciel-jour": "#fff6e8",
      "ciel-crepuscule": "#f0cdb3",
      "ciel-braise": "#f3d3bd",
      soleil: "#d98b2b",
      "soleil-encre": "#9a5a12",
      isha: "#4a3a52",
      hizb: "#1b6e51",
      formation: "#6b3f7d",
    },
  },
  merzouga: {
    sombre: true,
    couleurs: {
      ink: "#f4e9d8",
      "ink-soft": "#e6d6bd",
      "text-muted": "#b8a58c",
      "text-secondary": "#86776a",
      "text-tertiary": "#86776a",
      hairline: "#2c2438",
      canvas: "#17121f",
      "surface-secondary": "#0e0b14",
      "surface-secondary-hover": "#1f1929",
      "surface-warm": "#2a2235",
      "surface-manilla": "#231c18",
      "surface-kraft": "#2d2319",
      brand: "#e8a84b",
      "brand-hover": "#f2bf6c",
      "brand-soft": "#2b2114",
      "accent-clay": "#f08a4b",
      "accent-coral": "#3a1c1f",
      "accent-fig": "#c39bff",
      "accent-cactus": "#13291f",
      "accent-olive": "#6dd3a0",
      "accent-sky": "#86b6ff",
      "accent-heather": "#241c34",
      "accent-deep": "#ff7b6e",
      inverse: "#f4e9d8",
      "neutre-fort": "#3b3146",
      neutre: "#6b5d78",
      "neutre-profond": "#a595b1",
      "ciel-nuit": "#0b0915",
      "ciel-aube": "#2a1c2e",
      "ciel-jour": "#2b2019",
      "ciel-crepuscule": "#3a2419",
      "ciel-braise": "#47291a",
      soleil: "#f2b24d",
      "soleil-encre": "#f2b24d",
      isha: "#c8b8d9",
      hizb: "#5fd1bd",
      formation: "#b79cff",
    },
  },
  aube: {
    sombre: false,
    couleurs: {
      ink: "#2a1f38",
      "ink-soft": "#3b2e4c",
      "text-muted": "#62527a",
      "text-secondary": "#8a7a9b",
      "text-tertiary": "#8a7a9b",
      hairline: "#e5d9e8",
      canvas: "#fffbfd",
      "surface-secondary": "#f6f0f7",
      "surface-secondary-hover": "#efe6f1",
      "surface-warm": "#eadfee",
      "surface-manilla": "#fff5ea",
      "surface-kraft": "#fde8cf",
      brand: "#7c3aed",
      "brand-hover": "#6d28d9",
      "brand-soft": "#f1e8fb",
      "accent-clay": "#e8742c",
      "accent-coral": "#fbe1e4",
      "accent-fig": "#8b5cf6",
      "accent-cactus": "#dcf2e6",
      "accent-olive": "#136b4b",
      "accent-sky": "#3b7fd4",
      "accent-heather": "#ebe3f7",
      "accent-deep": "#b4233a",
      inverse: "#2a1f38",
      "neutre-fort": "#d7cadd",
      neutre: "#a897b3",
      "neutre-profond": "#75648a",
      "ciel-nuit": "#e6dcef",
      "ciel-aube": "#fadbd8",
      "ciel-jour": "#fff6f2",
      "ciel-crepuscule": "#f5d2d8",
      "ciel-braise": "#f8d6cf",
      soleil: "#f08c3c",
      "soleil-encre": "#9c4316",
      isha: "#4b3b63",
      hizb: "#1d6f64",
      formation: "#5b3ec4",
    },
  },
  crepuscule: {
    sombre: true,
    couleurs: {
      ink: "#fbeee6",
      "ink-soft": "#f0dcd0",
      "text-muted": "#c9a9a6",
      "text-secondary": "#9a7f82",
      "text-tertiary": "#9a7f82",
      hairline: "#3b2533",
      canvas: "#24161f",
      "surface-secondary": "#1a0f16",
      "surface-secondary-hover": "#2e1c28",
      "surface-warm": "#3a2432",
      "surface-manilla": "#2a1b18",
      "surface-kraft": "#33211a",
      brand: "#ff8a5c",
      "brand-hover": "#ffa37e",
      "brand-soft": "#3a1e1c",
      "accent-clay": "#ff9f5a",
      "accent-coral": "#3d1b22",
      "accent-fig": "#d4a5ff",
      "accent-cactus": "#16302a",
      "accent-olive": "#7ed9ae",
      "accent-sky": "#8fb8ff",
      "accent-heather": "#2d1d33",
      "accent-deep": "#ff7a85",
      inverse: "#fbeee6",
      "neutre-fort": "#4a3240",
      neutre: "#7d6272",
      "neutre-profond": "#b39aa8",
      "ciel-nuit": "#140b14",
      "ciel-aube": "#3a2033",
      "ciel-jour": "#3a2628",
      "ciel-crepuscule": "#4d2a2a",
      "ciel-braise": "#5c2f26",
      soleil: "#ff9f5a",
      "soleil-encre": "#ffb37a",
      isha: "#d9c3d3",
      hizb: "#6fd6c3",
      formation: "#c2a6ff",
    },
  },
};
